export interface VideoData {
  repoOwner: string;
  repoName: string;
  description: string | null;
  stars: number;
  forks: number;
  language: string | null;
  topics: string[];
  size: number;
  openIssues: number;
  summary: string;
  llmModel: string;
  lang: string;
  durationMs?: number;
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function fmt(n: number): string {
  return n >= 1000 ? `${(n / 1000).toFixed(1)}k` : String(n);
}

export function generateVideoHtml(data: VideoData): string {
  const repo = `${data.repoOwner}/${data.repoName}`;
  const summaryLines = data.summary
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .slice(0, 20);

  const topics = data.topics.slice(0, 6).map((t) => `#${t}`).join('  ');
  const elapsed = data.durationMs ? `${(data.durationMs / 1000).toFixed(1)}s` : '—';

  // Scene definitions: each scene is an array of { delay (ms), type, text, color }
  // type: 'cmd' | 'out' | 'blank' | 'box-start' | 'box-line' | 'box-end'
  const C = {
    green: '#4ade80',
    amber: '#fbbf24',
    cyan: '#22d3ee',
    purple: '#a78bfa',
    orange: '#f97316',
    gray: '#9ca3af',
    dim: '#4b5563',
    white: '#e0e0e0',
    red: '#f87171',
  };

  interface Line { delay: number; html: string; typewriter?: boolean; }

  const lines: Line[] = [];
  let t = 0;

  const push = (delay: number, html: string, typewriter = false) => {
    lines.push({ delay: t, html, typewriter });
    t += delay;
  };

  const col = (text: string, color: string) =>
    `<span style="color:${color}">${esc(text)}</span>`;
  const dim = (text: string) => col(text, C.dim);
  const grn = (text: string) => col(text, C.green);
  const amb = (text: string) => col(text, C.amber);
  const cyn = (text: string) => col(text, C.cyan);
  const wht = (text: string) => col(text, C.white);
  const prp = (text: string) => col(text, C.purple);

  // ── Scene 0: Intro ───────────────────────────────────────────────────
  push(800, `${dim('// terminal.social — Forkverse')}`);
  push(600, '');

  // ── Scene 1: Command ─────────────────────────────────────────────────
  push(400, `${grn('$')} ${wht('analyze')} ${dim('--repo=')}${amb(repo)} \\`, true);
  push(300, `    ${dim('--output=')}${cyn('video')} \\`);
  push(300, `    ${dim('--model=')}${prp(data.llmModel)}`);
  push(600, '');

  // ── Scene 2: GitHub Metadata ─────────────────────────────────────────
  push(200, `${grn('>')} fetching repo metadata...`);
  push(500, `${grn('>')} ${dim('repo:')} ${amb(repo)}`);
  if (data.description) {
    push(300, `${grn('>')} ${dim('desc:')} ${wht(data.description.slice(0, 80))}`);
  }
  push(300, `${grn('>')} ${dim('stars:')} ${col(fmt(data.stars), C.amber)}  ${dim('forks:')} ${col(fmt(data.forks), C.cyan)}  ${dim('issues:')} ${col(String(data.openIssues), C.orange)}`);
  if (data.language) {
    push(300, `${grn('>')} ${dim('lang:')} ${prp(data.language)}  ${dim('size:')} ${wht(data.size + 'kb')}`);
  }
  if (topics) {
    push(300, `${grn('>')} ${dim('topics:')} ${cyn(topics)}`);
  }
  push(700, '');

  // ── Scene 3: Analysis ────────────────────────────────────────────────
  push(200, `${grn('>')} analyzing structure...`);
  push(400, `${grn('>')} generating summary...`);
  push(500, '');
  push(200, `${dim('// analysis')}`);
  push(400, '');

  for (const line of summaryLines) {
    push(120, wht(line));
  }
  push(800, '');

  // ── Scene 4: Complete ────────────────────────────────────────────────
  push(300, `${grn('✓ analysis complete')}`);
  push(500, '');
  push(200, `${dim('┌─')} ${wht('Summary')} ${'─'.repeat(40)}`);
  push(200, `${dim('│')}  ${dim('repo')}      ${amb(repo)}`);
  push(200, `${dim('│')}  ${dim('model')}     ${prp(data.llmModel)}`);
  push(200, `${dim('│')}  ${dim('language')}  ${data.language ? prp(data.language) : dim('unknown')}`);
  push(200, `${dim('│')}  ${dim('stars')}     ${col(fmt(data.stars), C.amber)}`);
  push(200, `${dim('│')}  ${dim('elapsed')}   ${wht(elapsed)}`);
  push(200, `${dim('└')}${'─'.repeat(47)}`);
  push(800, '');

  // ── Scene 5: Credits ─────────────────────────────────────────────────
  push(400, `${dim('// generated by Forkverse · terminal.social')}`);
  push(600, `${grn('$')} ${col('_', C.green)}`);

  const totalMs = t + 1000;

  // Serialize lines to JSON for JS
  const linesJson = JSON.stringify(lines);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>$ analyze --repo=${esc(repo)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    html, body {
      background: #1a1a2e;
      color: #e0e0e0;
      font-family: 'Courier New', 'Consolas', 'Menlo', monospace;
      font-size: 14px;
      line-height: 1.6;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
    }
    #header {
      background: #0d1117;
      padding: 8px 16px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      border-bottom: 1px solid #1f2937;
      position: sticky;
      top: 0;
      z-index: 10;
    }
    #header-left { color: #4b5563; font-size: 11px; }
    #header-title { color: #9ca3af; font-size: 11px; }
    #terminal {
      flex: 1;
      padding: 24px 28px 80px;
      overflow-y: auto;
      max-width: 900px;
      width: 100%;
      margin: 0 auto;
    }
    .line {
      display: block;
      min-height: 1.6em;
      opacity: 0;
      transform: translateY(2px);
      transition: opacity 0.2s, transform 0.2s;
      white-space: pre-wrap;
      word-break: break-word;
    }
    .line.visible {
      opacity: 1;
      transform: none;
    }
    #progress-bar {
      position: fixed;
      bottom: 0;
      left: 0;
      right: 0;
      height: 3px;
      background: #0d1117;
      z-index: 10;
    }
    #progress-fill {
      height: 100%;
      background: #4ade80;
      width: 0%;
      transition: width 0.1s linear;
    }
    #controls {
      position: fixed;
      bottom: 12px;
      right: 16px;
      display: flex;
      gap: 8px;
      z-index: 20;
    }
    button {
      background: rgba(74,222,128,0.1);
      border: 1px solid rgba(74,222,128,0.3);
      color: #4ade80;
      font-family: inherit;
      font-size: 11px;
      padding: 4px 10px;
      cursor: pointer;
    }
    button:hover { background: rgba(74,222,128,0.2); }
    #cursor {
      display: inline-block;
      width: 8px;
      height: 1em;
      background: #4ade80;
      animation: blink 1s step-end infinite;
      vertical-align: text-bottom;
      margin-left: 2px;
    }
    @keyframes blink { 0%,100%{opacity:1} 50%{opacity:0} }
    .typewriter-cursor { display: none; }
  </style>
</head>
<body>
  <div id="header">
    <span id="header-left">terminal.social</span>
    <span id="header-title">$ analyze --repo=${esc(repo)}</span>
  </div>

  <div id="terminal">
    <div id="lines"></div>
    <div id="cursor"></div>
  </div>

  <div id="progress-bar"><div id="progress-fill"></div></div>

  <div id="controls">
    <button id="btn-restart">↺ restart</button>
    <button id="btn-speed">2× speed</button>
  </div>

  <script>
    const LINES = ${linesJson};
    const TOTAL_MS = ${totalMs};
    let speedMult = 1;
    let timers = [];
    let startTime = 0;
    let playing = false;
    let progTimer = null;

    function clearAll() {
      timers.forEach(clearTimeout);
      timers = [];
      if (progTimer) clearInterval(progTimer);
      progTimer = null;
      playing = false;
    }

    function play() {
      clearAll();
      document.getElementById('lines').innerHTML = '';
      document.getElementById('cursor').style.display = 'inline-block';
      document.getElementById('progress-fill').style.width = '0%';
      startTime = Date.now();
      playing = true;

      LINES.forEach(function(line, i) {
        var t = setTimeout(function() {
          var el = document.createElement('div');
          el.className = 'line';
          el.innerHTML = line.html || '&nbsp;';
          document.getElementById('lines').appendChild(el);
          requestAnimationFrame(function() {
            requestAnimationFrame(function() { el.classList.add('visible'); });
          });
          // Scroll to bottom
          var term = document.getElementById('terminal');
          term.scrollTop = term.scrollHeight;
        }, line.delay / speedMult);
        timers.push(t);
      });

      // Progress bar
      progTimer = setInterval(function() {
        var elapsed = (Date.now() - startTime) * speedMult;
        var pct = Math.min(100, (elapsed / TOTAL_MS) * 100);
        document.getElementById('progress-fill').style.width = pct + '%';
        if (pct >= 100) { clearInterval(progTimer); }
      }, 100);
    }

    document.getElementById('btn-restart').addEventListener('click', function() { play(); });
    document.getElementById('btn-speed').addEventListener('click', function() {
      speedMult = speedMult === 1 ? 2 : speedMult === 2 ? 4 : 1;
      this.textContent = speedMult === 1 ? '2× speed' : speedMult === 2 ? '4× speed' : '1× speed';
    });

    // Auto-play on load
    window.addEventListener('load', function() { setTimeout(play, 500); });
  </script>
</body>
</html>`;
}
