/**
 * Analysis Worker — processes analysis jobs from the queue.
 * Extracted from routes/analyze.ts for separation of concerns.
 *
 * In MVP: runs in-process via setInterval polling.
 * In production: can be run as a separate process with BullMQ/Redis.
 */
import type { Database } from 'better-sqlite3';
import type { Logger } from 'pino';
import { createProvider } from '@forkverse/llm';
import type { AnalysisProgress } from '@forkverse/shared';
import { generatePptx } from './generatePptx.js';
import { generateVideoHtml } from './generateVideo.js';
import { writeFileSync } from 'node:fs';
import path from 'node:path';

const UPLOADS_DIR = path.join(process.cwd(), 'uploads', 'analyses');

interface AnalysisRow {
  id: string;
  user_id: string;
  repo_owner: string;
  repo_name: string;
  output_type: string;
  llm_model: string;
  lang: string;
  options_json: string;
}

interface JobRow {
  id: string;
  analysis_id: string;
  retries: number;
  max_retries: number;
}

interface LlmKeyRow {
  api_key: string;
  base_url?: string;
}

interface GithubRepoResponse {
  full_name: string;
  description: string | null;
  stargazers_count: number;
  forks_count: number;
  language: string | null;
  topics: string[];
  size: number;
  open_issues_count: number;
  default_branch: string;
  created_at: string;
  updated_at: string;
}

function modelToProvider(model: string): string {
  if (model.startsWith('claude')) return 'anthropic';
  if (model.startsWith('gpt') || model.startsWith('o1') || model.startsWith('o3') || model.startsWith('o4')) return 'openai';
  if (model.startsWith('gemini')) return 'gemini';
  if (model.startsWith('llama')) return 'ollama';
  return 'api';
}

async function pushToGithub(
  db: Database,
  userId: string,
  repoOwner: string,
  repoName: string,
  summary: string,
  llmModel: string,
  lang: string,
  logger: Logger,
): Promise<boolean> {
  const user = db.prepare('SELECT github_access_token FROM users WHERE id = ?')
    .get(userId) as { github_access_token: string | null } | undefined;

  if (!user?.github_access_token) return false;

  const filePath = 'ANALYSIS.md';
  const date = new Date().toISOString().split('T')[0];
  const content = `# Repository Analysis\n\n> Generated by [Forkverse](https://terminal.social) on ${date}\n> Model: \`${llmModel}\` · Language: ${lang}\n\n---\n\n${summary}\n\n---\n\n*This analysis was auto-generated by Forkverse (\`$ analyze --repo=${repoOwner}/${repoName}\`).*\n`;

  const headers = {
    Authorization: `Bearer ${user.github_access_token}`,
    'User-Agent': 'Forkverse',
    Accept: 'application/vnd.github+json',
    'Content-Type': 'application/json',
  };

  try {
    let existingSha: string | undefined;
    const getRes = await fetch(
      `https://api.github.com/repos/${repoOwner}/${repoName}/contents/${filePath}`,
      { headers },
    );
    if (getRes.ok) {
      const existing = (await getRes.json()) as { sha: string };
      existingSha = existing.sha;
    }

    const body: Record<string, string> = {
      message: `docs: update repository analysis\n\nGenerated by Forkverse (${llmModel})`,
      content: Buffer.from(content, 'utf-8').toString('base64'),
      branch: 'main',
    };
    if (existingSha) body.sha = existingSha;

    const putRes = await fetch(
      `https://api.github.com/repos/${repoOwner}/${repoName}/contents/${filePath}`,
      { method: 'PUT', headers, body: JSON.stringify(body) },
    );

    return putRes.ok;
  } catch {
    logger.warn({ repoOwner, repoName }, 'GitHub push error');
    return false;
  }
}

/**
 * Execute a single analysis job.
 */
export async function executeAnalysis(
  db: Database,
  analysisId: string,
  logger: Logger,
): Promise<void> {
  const analysis = db.prepare('SELECT * FROM analyses WHERE id = ?').get(analysisId) as AnalysisRow | undefined;
  if (!analysis) throw new Error(`Analysis ${analysisId} not found`);

  const { user_id: userId, repo_owner: repoOwner, repo_name: repoName, output_type: outputType, llm_model: llmModel, lang } = analysis;
  const options = JSON.parse(analysis.options_json) as { userPrompt?: string };
  const userPrompt = options.userPrompt;
  const startedAt = Date.now();

  const setProgress = (progress: AnalysisProgress[]) => {
    db.prepare('UPDATE analyses SET progress_json = ? WHERE id = ?')
      .run(JSON.stringify(progress), analysisId);
  };

  const isPptx = outputType === 'pptx';
  const isVideo = outputType === 'video';
  const thirdStep = isPptx ? 'generating presentation' : isVideo ? 'generating video' : 'generating summary';
  const progress: AnalysisProgress[] = [
    { name: 'fetching repo metadata', status: 'active' },
    { name: 'analyzing structure', status: 'pending' },
    { name: thirdStep, status: 'pending' },
    { name: 'pushing to repository', status: 'pending' },
  ];
  setProgress(progress);
  db.prepare("UPDATE analyses SET status = 'processing' WHERE id = ?").run(analysisId);

  // Step 1: Fetch GitHub metadata
  const ghRes = await fetch(`https://api.github.com/repos/${repoOwner}/${repoName}`, {
    headers: { 'User-Agent': 'Forkverse', Accept: 'application/vnd.github.v3+json' },
  });
  if (!ghRes.ok) throw new Error(`GitHub API error: ${ghRes.status}`);
  const repo = (await ghRes.json()) as GithubRepoResponse;

  progress[0] = { name: 'fetching repo metadata', status: 'done', detail: `${repo.stargazers_count} stars` };
  progress[1] = { name: 'analyzing structure', status: 'active' };
  setProgress(progress);

  // Step 2: LLM analysis
  const providerName = modelToProvider(llmModel);
  const keylessProviders = new Set(['ollama']);
  let credentials: { apiKey?: string; baseUrl?: string } = {};
  if (!keylessProviders.has(providerName)) {
    const keyRow = db.prepare('SELECT api_key, base_url FROM user_llm_keys WHERE user_id = ? AND provider = ?')
      .get(userId, providerName) as LlmKeyRow | undefined;
    if (keyRow) {
      credentials = { apiKey: keyRow.api_key, ...(keyRow.base_url ? { baseUrl: keyRow.base_url } : {}) };
    }
  }

  progress[1] = { name: 'analyzing structure', status: 'done', detail: `${repo.language ?? 'unknown'} · ${repo.size}kb` };
  progress[2] = { name: 'generating summary', status: 'active' };
  setProgress(progress);

  const langName = lang === 'ko' ? 'Korean' : lang === 'ja' ? 'Japanese' : lang === 'zh' ? 'Chinese' : 'English';
  const prompt = `Analyze the GitHub repository ${repoOwner}/${repoName}.

Repository info:
- Description: ${repo.description ?? 'none'}
- Primary language: ${repo.language ?? 'unknown'}
- Stars: ${repo.stargazers_count}, Forks: ${repo.forks_count}
- Topics: ${repo.topics.join(', ') || 'none'}
- Size: ${repo.size}kb
- Open issues: ${repo.open_issues_count}
- Default branch: ${repo.default_branch}
${userPrompt ? `\nUser focus: ${userPrompt}\n` : ''}
Respond ONLY with a valid JSON object (no markdown fences, no extra text) with these exact keys:
{
  "summary": "2-3 sentence overview of what the project does and its purpose",
  "techStack": "List the main technologies, frameworks, and tools used",
  "architecture": "Describe the project's architecture, structure, and key design patterns",
  "strengths": "Notable strengths and well-designed aspects",
  "risks": "Potential risks, technical debt, or areas of concern",
  "improvements": "Suggested improvements and recommendations",
  "cliView": "A CLI-style summary like: analyze --repo=${repoOwner}/${repoName} → <one-line verdict>"
}

Each value should be 2-5 sentences. Reply in ${langName}. Be specific and technical.
${userPrompt ? `Pay special attention to: "${userPrompt}"` : ''}`;

  let summary = '';
  let sectionsJson: string | null = null;
  try {
    const provider = createProvider(providerName, credentials);
    const rawResponse = await provider.translate({
      message: prompt, sourceLang: 'en', targetLang: lang,
      intent: 'formal', emotion: 'neutral', model: llmModel,
    });

    try {
      const cleaned = rawResponse.replace(/```(?:json)?\s*/g, '').replace(/```\s*/g, '').trim();
      const parsed = JSON.parse(cleaned) as Record<string, string>;
      if (parsed.summary && parsed.techStack && parsed.architecture) {
        sectionsJson = JSON.stringify(parsed);
        summary = [parsed.summary, parsed.techStack, parsed.architecture, parsed.strengths, parsed.risks, parsed.improvements].filter(Boolean).join('\n\n');
      } else {
        summary = rawResponse;
      }
    } catch {
      summary = rawResponse;
    }
  } catch {
    summary = `Analysis of ${repoOwner}/${repoName}: ${repo.description ?? 'No description available.'}`;
  }

  if (!sectionsJson && summary) {
    const paragraphs = summary.split('\n\n').filter(Boolean);
    const fallback = {
      summary: paragraphs[0] ?? summary,
      techStack: paragraphs[1] ?? '',
      architecture: paragraphs[2] ?? '',
      strengths: paragraphs[3] ?? '',
      risks: paragraphs[4] ?? '',
      improvements: paragraphs[5] ?? '',
      cliView: `analyze --repo=${repoOwner}/${repoName} → completed`,
    };
    sectionsJson = JSON.stringify(fallback);
  }

  // Step 3: Generate output
  let resultUrl: string | null = null;
  if (isVideo) {
    try {
      const { mkdirSync } = await import('node:fs');
      mkdirSync(UPLOADS_DIR, { recursive: true });
      const filename = `${analysisId}.html`;
      const filePath = path.join(UPLOADS_DIR, filename);
      const html = generateVideoHtml({
        repoOwner, repoName, description: repo.description,
        stars: repo.stargazers_count, forks: repo.forks_count,
        language: repo.language, topics: repo.topics, size: repo.size,
        openIssues: repo.open_issues_count, summary, llmModel, lang,
        durationMs: Date.now() - startedAt,
      });
      writeFileSync(filePath, html, 'utf-8');
      resultUrl = filePath;
    } catch (err) { logger.warn({ err }, 'Video generation failed'); }
    progress[2] = { name: 'generating video', status: 'done', detail: resultUrl ? 'ready to view' : 'summary only' };
  } else if (isPptx) {
    try {
      const filename = `${analysisId}.pptx`;
      const filePath = await generatePptx({
        repoOwner, repoName, description: repo.description,
        stars: repo.stargazers_count, forks: repo.forks_count,
        language: repo.language, topics: repo.topics, size: repo.size,
        openIssues: repo.open_issues_count, defaultBranch: repo.default_branch,
        createdAt: repo.created_at, updatedAt: repo.updated_at,
        summary, llmModel, lang,
      }, UPLOADS_DIR, filename);
      resultUrl = filePath;
    } catch (err) { logger.warn({ err }, 'PPTX generation failed'); }
    progress[2] = { name: 'generating presentation', status: 'done', detail: resultUrl ? 'ready for download' : 'summary only' };
  } else {
    progress[2] = { name: 'generating summary', status: 'done' };
  }
  setProgress(progress);

  // Step 4: Push to GitHub
  progress[3] = { name: 'pushing to repository', status: 'active' };
  setProgress(progress);
  const pushed = await pushToGithub(db, userId, repoOwner, repoName, summary, llmModel, lang, logger);
  progress[3] = {
    name: 'pushing to repository',
    status: pushed ? 'done' : 'failed',
    detail: pushed ? 'ANALYSIS.md committed' : 'skipped (no write access)',
  };
  setProgress(progress);

  // Save result
  const durationMs = Date.now() - startedAt;
  db.prepare(`
    UPDATE analyses SET status = 'completed', result_summary = ?, result_sections_json = ?,
      result_url = ?, progress_json = ?, duration_ms = ?
    WHERE id = ?
  `).run(summary, sectionsJson, resultUrl, JSON.stringify(progress), durationMs, analysisId);
}

/**
 * Process a single job from the queue.
 */
async function processJob(db: Database, job: JobRow, logger: Logger): Promise<void> {
  db.prepare("UPDATE analysis_jobs SET status = 'active', started_at = datetime('now') WHERE id = ?").run(job.id);

  try {
    await executeAnalysis(db, job.analysis_id, logger);
    db.prepare("UPDATE analysis_jobs SET status = 'completed', completed_at = datetime('now') WHERE id = ?").run(job.id);
    logger.info({ jobId: job.id, analysisId: job.analysis_id }, 'Job completed');
  } catch (err) {
    const retries = job.retries + 1;
    const errMsg = err instanceof Error ? err.message : 'unknown error';

    if (retries >= job.max_retries) {
      // Mark as dead — no more retries
      db.prepare("UPDATE analysis_jobs SET status = 'dead', retries = ?, error = ?, completed_at = datetime('now') WHERE id = ?")
        .run(retries, errMsg, job.id);
      db.prepare("UPDATE analyses SET status = 'failed' WHERE id = ?").run(job.analysis_id);
      logger.error({ jobId: job.id, retries, err: errMsg }, 'Job permanently failed');
    } else {
      // Schedule retry with exponential backoff (2^retries seconds)
      const backoffSec = Math.pow(2, retries);
      db.prepare(`UPDATE analysis_jobs SET status = 'pending', retries = ?, error = ?, next_retry_at = datetime('now', '+${backoffSec} seconds') WHERE id = ?`)
        .run(retries, errMsg, job.id);
      logger.warn({ jobId: job.id, retries, backoffSec, err: errMsg }, 'Job failed, scheduling retry');
    }
  }
}

/**
 * Start the worker polling loop.
 * Picks up pending jobs and processes them sequentially.
 */
export function startWorker(db: Database, logger: Logger, intervalMs = 2000): () => void {
  let running = true;

  const poll = async () => {
    if (!running) return;

    try {
      // Pick the oldest pending job that's ready for processing
      const job = db.prepare(`
        SELECT id, analysis_id, retries, max_retries FROM analysis_jobs
        WHERE status = 'pending'
          AND (next_retry_at IS NULL OR next_retry_at <= datetime('now'))
        ORDER BY created_at ASC
        LIMIT 1
      `).get() as JobRow | undefined;

      if (job) {
        await processJob(db, job, logger);
      }
    } catch (err) {
      logger.error({ err }, 'Worker poll error');
    }

    if (running) {
      setTimeout(poll, intervalMs);
    }
  };

  void poll();
  logger.info('Analysis worker started');

  return () => {
    running = false;
    logger.info('Analysis worker stopped');
  };
}
